version: '3.3'

networks:
  em:
    driver: bridge
volumes:
  db:
    driver: local
  webapp:
    driver: local
  backoffice:
    driver: local
  api:
    driver: local

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes: 
      - db:/var/lib/postgresql/data:delegated
    networks:
      - em

  ########################
  # WebApp server
  ########################
  webapp:
    container_name: em-webapp
    build:
      context: './'
      dockerfile: docker/webapp/Dockerfile.dev
      args:
        - TZ=${TZ}
    image: em-webapp
    env_file: .env
    volumes:
      - ./projects/webapp:/usr/app/webapp:delegated
    ports:
      - '${WEBAPP_PORT}:3000'
    links:
      - db:db
    depends_on:
      - 'db'
      - 'api'
    networks:
      - 'em'

  ########################
  # Backoffice server
  ########################
  backoffice:
    container_name: em-backoffice
    build:
      context: './'
      dockerfile: docker/backoffice/Dockerfile.dev
      args:
        - TZ=${TZ}
    image: em-backoffice
    volumes:
      - ./projects/backoffice:/usr/app/backoffice:delegated
    ports:
      - '${BACKOFFICE_PORT}:4200'
    links:
      - db:db
    depends_on:
      - 'db'
      - 'api'
    networks:
      - 'em'

  ########################
  # API Server
  ########################
  api:
    container_name: em-api
    build:
      context: './'
      dockerfile: docker/api/Dockerfile.dev
      args:
        - TZ=${TZ}
    image: em-api
    env_file: .env
    links:
      - db:db
    depends_on:
      - 'db'
    ports:
      - '${API_PORT}:1337'
    volumes:
      - ./projects/api/.env:/usr/app/api/.env
    networks:
      - 'em'